version: '3.4'
services:
  drupal.test:
    hostname: ${HOSTNAME}
    image: codementality/apache2
    expose:
      - 9000
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./:/var/www/html:cached # User-guided caching      
    environment:
      TZ: 'EST5EDT'
      WEB_ALIAS_DOMAIN: 'www.${HOSTNAME}'
      WEB_DOCUMENT_ROOT: '/var/www/html/docroot'
    depends_on:
      - php
      - db

  php:
    image: codementality/php7.3
    volumes:
      - ./:/var/www/html:cached # User-guided caching
      - ./docker/php/conf.d/php.ini:/etc/php/7.3/fpm/conf.d/50-overrides.ini
    environment:
      TZ: 'EST5EDT'
      PHP_IDE_CONFIG: "serverName=docker"
      # Switch remote_host to 127.0.0.1 for Linux.
      # Switch remote_enable to 0 to disable xDebug within the container.  See following two lines.
      XDEBUG_CONFIG: "remote_enable=1 remote_host=10.254.254.254"
      #XDEBUG_CONFIG: "remote_enable=0"
      COMPOSER_MEMORY_LIMIT: -1
      WEB_ALIAS_DOMAIN: 'www.${HOSTNAME}'
      WEB_PHP_SOCKET: 'php:9000'
      WEB_DOCUMENT_ROOT: '/var/www/html/docroot'
    depends_on:
      - db

  db:
    hostname: db.${HOSTNAME}
    image: mariadb
    environment:
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
    ports:
      - 33306:3306
    volumes:
      - dbdata:/var/lib/mysql

  solr.drupal.test:
    hostname: solr.${HOSTNAME}
    image: solr:6.6
    ports:
     - 8983:8983
    volumes:
      - solr:/opt/solr/server/solr/d8
      - ./config/solr/6.x:/solr-conf/conf
    entrypoint:
      - docker-entrypoint.sh
      - solr-precreate
      - d8
      - /solr-conf
    depends_on:
      - drupal.test

  mailhog:
    image: mailhog/mailhog
    ports:
      - 8025
    depends_on:
      - drupal.test

  memcached:
    image: memcached:1.5
    ports:
      - 11211
    depends_on:
      - drupal.test
      - php

  fetools:
    image: codementality/fetools:latest
    depends_on:
      - drupal.test
    volumes:
      - ./themesrc/themes:/data/themesrc/themes
      - ./docroot:/data/docroot

  selenium:
    image: selenium/standalone-chrome:3.14.0
    ports:
      - 4444:4444
    volumes:
      - /dev/shm:/dev/shm
    depends_on:
      - drupal.test
      - php

  pa11y:
    image: prometsource/docker-pa11y-ci:0.10
    volumes:
       - ./tests/pa11y/wcag2-config.json:/workspace/wcag2-config.json
    depends_on:
      - drupal.test

volumes:
## persistent data volume for mysql data
  dbdata:
    driver: local
## persistent data volume for Solr
  solr:
    driver: local
